version: '3'
services:

  postgrestask:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: olympus
    networks:
      - leapx

  postgresidentity:
    image: postgres
    ports:
      - '5431:5431'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: identity
    networks:
      - leapx


  identity:
      image: identity
      build:
        context: ./identity/
        dockerfile: Dockerfile
      depends_on:
        - postgresidentity 
      networks:
        - leapx
  
  task:
      image: task
      build:
        context: ./Backend/task-ms/
        dockerfile: Dockerfile
      depends_on:
        - postgrestask 
      networks:
        - leapx


networks:
  leapx:
    driver: bridge
