version: '3'
services:

  postgrestask:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: olympus
    networks:
      - leapx

  identity:
      image: identity
      build:
        context: ./identity/
        dockerfile: Dockerfile
      ports:
      - '8081:8081'
      depends_on:
        - postgrestask 
      networks:
        - leapx
  
  task:
      image: task
      build:
        context: ./Backend/task-ms/
        dockerfile: Dockerfile
      ports:
        - '8082:8082'
      depends_on:
        - postgrestask 
      networks:
        - leapx


networks:
  leapx:
    driver: bridge
