version: '3'
services:

  postgrestask:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: olympus
    networks:
      - leapx
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "olympus", "-U", "dev_admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgresidentity:
    image: postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: identity
    networks:
      - leapx
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "identity", "-U", "dev_admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  identity:
      image: identity
      build:
        context: ./Identity/
        dockerfile: Dockerfile
      ports:
      - '8081:8081'
      depends_on:
        postgresidentity:
          condition: service_healthy 
      networks:
        - leapx
  
  task:
      image: task
      build:
        context: ./Backend/task-ms/
        dockerfile: Dockerfile
      ports:
        - '8082:8082'
      depends_on:
        postgrestask:
          condition: service_healthy 
      networks:
        - leapx


networks:
  leapx:
    driver: bridge
